### ISSUE TITLE
Refresh Printer Error

### ISSUE THREAD

**Issue by MalibuXP** [Clon1998/mobileraker_companion#64]
Hi, my english is very bad. Sorry.

I Have an error message.

Exception:
 MobilerakerException{Missing field: print, parentException: null, parentStack: null}

#0      PrinterBuilder.build (package:common/data/dto/machine/printer.dart:94)
#1      PrinterService.refreshPrinter (package:common/service/moonraker/printer_service.dart:214)
<asynchronous suspension>

I have Version 2.6.6
So what can I do?

**Comment by MalibuXP** [comment]
OMG Iam an Idiot.

Mainsail.cfg was not includet in the Printer.cfg . 
I didnt save it in the past.
So now it works. Thanks for the brainstorming idea that i have look into the Printer.cfg.

Thanks
